# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "ihub-bot"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: docker
    directory: /nacos
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /one-api
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /sentinel
    schedule:
      interval: daily
