# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  release:
    types: published

jobs:
  push_to_registry:
    name: Push Docker ${{ matrix.image_name }} image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        image_name: [nacos]
        nacos_version: [2.0.3]
    steps:
      - name: Extract Version
        id: version_step
        run: |
          echo "##[set-output name=version;]NACOS_VERSION=${{ matrix.${{ matrix.image_name }}_version }}"

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ihubpub/${{ matrix.image_name }}
          flavor: |
            latest=auto
            prefix=
            suffix=-${{ matrix.image_name }}-${{steps.version_step.outputs.version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.3.0
        with:
          context: ${{ matrix.image_name }}
          file: ${{ matrix.image_name }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{steps.version_step.outputs.version}}
